name: "Anthem Engineering"
description: "Anthem Engineering is a software, systems, and solutions company focused on rapidly developing capabilities that make a difference. We believe that technology exists to serve the mission, not to serve itself. We use the most advanced technology available to solve problems for our customers."

url: ""
permalink: pretty

#livereload: true     # You no longer need to include --livereload

sass:
    load_paths:
        - _sass
        - node_modules
exclude: []
